### ISSUE TITLE
Bring back #44 - case insensitive keywords

### ISSUE THREAD

**Issue by gerzytet** [TriggerReactor/TriggerReactor#223] opened 2019-10-19 02:12 UTC
Now that #187 is part of 2.2, we have case insensitive placeholder/executor names.
I think it’s a good idea to do the same for keywords too.  Lowercase keywords are easier to type and look more modern, which is a usability improvement.

The disadvantage is we will have to get rid of variables named the same as lowercase keywords which would have been previously valid.

**Comment by rkdrns4747** [comment] 2019-10-20 12:34
Keywords:
IF
ELSEIF
ELSE
ENDIF
IMPORT
WHILE
ENDWHILE
FOR
ENDFOR
SYNC
ENESYNC
ASYNC
ENDASYNC
IS

**Comment by Sayakie** [comment] 2023-07-20 06:00
Duplicate of #44

**Closed by Sayakie** 2023-07-20 06:00 UTC
Labels: domain:suggestion
