### ISSUE TITLE
Properly support arithmetic operations on long values

### ISSUE THREAD

**Issue by wysohn** [TriggerReactor/TriggerReactor#457] opened 2022-01-05 22:59 UTC
Use case example:
![image](https://user-images.githubusercontent.com/8789836/148301786-5ca9a3ab-9c83-41ad-aed0-b409afa8a9c6.png)

**Comment by Sayakie** [comment] 2022-02-28 00:47
Duplicate of #357

**Closed** 2022-09-18 04:00 UTC
Labels: domain:duplicate
